### ISSUE TITLE
New message Layout

### ISSUE THREAD

**Issue by AlexNi245** [corpus-ventures/dm3#1193]
## Current situation

the layout of the messenger component is in "left/right" style.

## Requirement

We need a second style ("user" style). In this style, all conversation participants are on the same side, identified by icon and name (see pic 01). More than two participants will be possible (group chat). The style should be configurable.

## Tasks

- [ ] Add a Settings section to switch between the old and the new layout.
- [ ] Add a flag at the local store to memorize the chosen layout.
- [ ] Add config parameter to configure it from outside
- [ ] Create a component for the second UI. (keep in mind that group chat might be possible in future)
- [ ] Testing

## Figma

https://www.figma.com/design/MrIgq5agEw1AX2JaxQ1JBs/dm3-embedded?node-id=2439-93

## Pictures

![image](https://github.com/user-attachments/assets/dfaf34cf-66bd-4c73-bf87-e776e168cf9c)
