### ISSUE TITLE
Unit tests for messenger widget client

### ISSUE THREAD

**Issue by Bhupesh-mfsi** [corpus-ventures/dm3#1199]
## Unit tests : Messenger widget

Implement unit tests for every acceptance criteria for each module mentioned in the below document.
https://www.notion.so/corpusventures/Acceptance-Criteria-Dm3-Messenger-Widget-5dbaba22de4d495c8673d6c59df6c5e7

### Tasks

- [ ] Setup cypress library in project
- [ ] Tests for Add conversation
- [ ] Tests for Top level alias
- [ ] Tests for Conversation order

##
**NOTE:** Use Cypress library to implement test cases
