### ISSUE TITLE
Support user sphere message storage

### ISSUE THREAD

**Issue by hai-ko** [corpus-ventures/dm3#68]
## Current
```mermaid
sequenceDiagram
    UI->>+BackendAPILib: getMessages()
    BackendAPILib->>+Backend: POST getMessages
    Backend-->>-BackendAPILib: Messages
    BackendAPILib-->>-UI: Messages

```
## Goal
```mermaid
sequenceDiagram
    UI->>+MessagingHandler: getMessages()
    MessagingHandler->>+BackendAPILib: getNewMessages()
    BackendAPILib->>+DeliveryService: POST getMessages
    DeliveryService-->>-BackendAPILib: Messages
    Note right of MessagingHandler: "new" messages
    BackendAPILib-->>-MessagingHandler: Messages

    MessagingHandler->>MessagingHandler: decryptedMessages()

    MessagingHandler->>+StorageLib: storeMessages()
    StorageLib-->>-MessagingHandler: success

    MessagingHandler->>+StorageLib: getConversation()
    Note right of MessagingHandler: "new" + "old" messages
    StorageLib-->>-MessagingHandler: Messages
    MessagingHandler-->>-UI: Messages
```

## Todo
- [x] Decide on storage framework
- [x] Implement messaging handler
- [x] Store outgoing messages
